let categories = [
    {
        clue: "Actor/Actress",
        choices: [
            "will smith",
            "brad pitt",
            "johnny depp",
            "leonardo dicaprio",
            "tom hanks",
            "harrison ford",
            "robert de niro",
            "michael caine",
            "robin williams",
            "denzel washington",
            "joaquin phoenix",
            "marlon brando",
            "morgan freeman",
            "gary oldman",
            "hugh jackman",
            "jamie foxx",
            "dwayne johnson",
            "christian bale",
            "anthony hopkins",
            "jim carrey",
            "sean penn",
            "sean connery",
            "john travolta",
            "brandon lee",
            "bruce willis",
            "jude law",
            "alec baldwin",
            "michael j fox",
            "christopher walken",
            "matt damon",
            "ben stiller",
            "kevin spacey",
            "russell crowe",
            "angelina jolie",
            "tom cruise",
            "arnold schwarzenegger",
            "sylvester stallone",
            "kate winslet",
            "christian bale",
            "keanu reeves",
            "nicolas cage",
            "hugh jackman",
            "edward norton",
            "charlize theron",
            "keira knightley",
            "vin diesel",
            "richard gere",
            "catherine zeta jones",
            "clive owen",
            "mel gibson",
            "george clooney",
            "jack nicholson",
            "scarlett johansson",
            "tom hardy",
            "orlando bloom",
            "ian mckellen",
            "antonio banderas",
            "guy pearce",
            "samuel l jackson",
            "sandra bullock",
            "meg ryan",
            "megan fox",
            "nicole kidman",
            "gerard butler",
            "simon baker",
            "cameron diaz",
            "katherine heigl",
            "jackie chan",
            "jennifer aniston",
            "eddie murphy",
            "meryl streep",
            "natalie portman",
            "martin lawrence",
            "drew barrymore",
            "al pacino",
            "jessica alba",
            "salma hayek",
            "penelope cruz",
            "jack black",
            "kevin costner",
            "steve martin",
            "milla jovovich",
            "elijah wood",
            "demi moore",
            "heath ledger",
            "eva mendes",
            "halle berry",
            "kirsten dunst",
            "leslie nielsen",
            "liv tyler",
            "robert redford",
            "ewan mcgregor",
            "paul newman",
            "danny devito",
            "will ferrell",
            "michelle pfeiffer",
            "kate beckinsale",
            "sharon stone",
            "winona ryder",
            "jane fonda",
            "kim basinger",
            "sarah michelle geller",
            "carmen electra",
            "cristina ricci",
            "mike myers",
            "alicia silverstone",
        ],
    },
    {
        clue: "Author",
        choices: [
            "william shakespeare",
            "emily dickinson",
            "h p lovecraft",
            "arthur conan doyle",
            "leo tolstoy",
            "edgar allan poe",
            "oscar wilde",
            "charles dickens",
            "john keats",
            "ernest hemingway",
            "robert louis stevenson",
            "aristotle",
            "jane austen",
            "plato",
            "agatha christie",
            "franz kafka",
            "mark twain",
            "stephen king",
            "ernest hemingway",
            "clive barker",
            "h g wells",
            "william butler yeats",
            "t s eliot",
            "lewis carroll",
            "virginia woolf",
            "bram stoker",
            "d h lawrence",
            "beatrix potter",
            "jules verne",
            "george orwell",
            "fyodor dostoevsky",
            "j r r tolkien",
            "john steinbeck",
            "james joyce",
            "c s lewis",
            "alexandre dumas",
            "f scott fitzgerald",
            "kurt vonnegut",
            "j k rowling",
            "william faulkner",
            "gabriel garcia marquez",
            "homer",
            "victor hugo",
            "charlotte bronte",
            "emily bronte",
            "ray bradbury",
            "paulo coelho",
            "dr seuss",
            "john grisham",
            "salman rusdie",
            "dan brown",
            "william blake",
            "graham greene",
            "jean paul sarte",
            "isaac asimov",
            "john irving",
            "umberto eco",
        ],
    },
    {
        clue: "Animal",
        choices: [
            "bear",
            "elephant",
            "tiger",
            "cheetah",
            "giraffe",
            "hippopotamus",
            "hamster",
            "mouse",
            "cat",
            "dog",
            "tasmanian devil",
            "koala",
            "raccoon",
            "deer",
            "monkey",
            "donkey",
            "goat",
            "horse",
            "rabbit",
            "guinea pig",
            "turkey",
            "anaconda",
            "angelfish",
            "antelope",
            "leopard",
            "fox",
            "wolf",
            "crab",
            "baboon",
            "badger",
            "bald eagle",
            "barracuda",
            "hedgehog",
            "black panther",
            "camel",
            "zebra",
            "caribou",
            "reindeer",
            "moose",
            "spider",
            "chameleon",
            "buffalo",
            "capybara",
            "centipede",
            "chimpanzee",
            "cougar",
            "cobra",
            "dragonfly",
            "duck",
            "dung beetle",
            "cricket",
            "dolphin",
            "shark",
            "flamingo",
            "goldfish",
            "squid",
            "gazelle",
            "sloth",
            "hyena",
            "impala",
            "komodo dragon",
            "lizard",
            "lynx",
            "kangaroo",
            "jellyfish",
            "hummingbird",
            "lobster",
            "locust",
            "mole",
            "parrot",
            "ostrich",
            "orca",
            "nightingale",
            "moth",
            "mosquito",
            "penguin",
            "peacock",
            "pelican",
            "otter",
            "owl",
            "rhinoceros",
            "rattlesnake",
            "rooster",
            "salamander",
            "praying mantis",
            "prawn",
            "porcupine",
            "polar bear",
            "piranha",
            "pig",
            "seahorse",
            "squirrel",
            "swordfish",
            "stork",
            "stingray",
            "termite",
            "ant",
            "wildebeast",
            "wasp",
            "walrus",
            "tortoise",
            "woodpecker",
            "wolverine",
            "wombat",
            "weasel",
            "zebra",
            "yak",
        ],
    },
    {
        clue: "Bird",
        choices: [
            "parrot",
            "peacock",
            "owl",
            "penguin",
            "sparrow",
            "hummingbird",
            "mallard",
            "ibis",
            "bluebird",
            "duck",
            "flamingo",
            "falcon",
            "eagle",
            "raven",
            "woodpecker",
            "vulture",
            "pelican",
            "quail",
            "nighthawk",
            "hawk",
            "kingfisher",
            "albatross",
            "auklet",
            "bittern",
            "blackbird",
            "bunting",
            "chickadee",
            "crow",
            "dove",
            "egret",
            "finch",
            "goose",
            "seagull",
            "magpie",
            "pigeon",
            "puffin",
            "sparrow",
            "swallow",
            "turkey",
            "chicken",
        ],
    },
    {
        clue: "Brand",
        choices: [
            "apple",
            "google",
            "nike",
            "adidas",
            "puma",
            "new balance",
            "samsung",
            "motorola",
            "nokia",
            "huawei",
            "coca cola",
            "pepsi",
            "toyota",
            "mercedes benz",
            "volkswagen",
            "ford",
            "volvo",
            "kia",
            "amazon",
            "netflix",
            "chanel",
            "microsoft",
            "paypal",
            "facebook",
            "wells fargo",
            "mcdonalds",
            "burger king",
            "ge",
            "disney",
            "louis vuitton",
            "intel",
            "cisco",
            "oracle",
            "verizon",
            "walmart",
            "budweiser",
            "heineken",
            "ibm",
            "marlboro",
            "bmw",
            "american express",
            "honda",
            "gucci",
            "nescafe",
            "home depot",
            "accenture",
            "starbucks",
            "mastercard",
            "ikea",
            "zara",
            "gillette",
            "hsbc",
            "audi",
            "sony",
            "ups",
            "bank of america",
            "chase",
            "siemens",
            "nestle",
            "cartier",
            "porsche",
            "espn",
            "adobe",
            "pampers",
            "corona",
            "ebay",
            "chevrolet",
            "red bull",
            "hp",
            "lancome",
            "santander",
            "rolex",
            "hyundai",
            "danone",
            "goldman sachs",
            "nintendo",
            "allianz",
            "dell",
            "caterpillar",
            "lego",
            "john deere",
            "ubs",
            "kfc",
            "ey",
            "fedex",
        ],
    },
    {
        clue: "Body Part",
        choices: [
            "finger",
            "elbow",
            "neck",
            "knee",
            "stomach",
            "nose",
            "shin",
            "ear",
            "eye",
            "thumb",
            "pelvis",
            "foot",
            "toe",
            "heel",
            "ankle",
            "head",
            "chin",
            "eyebrow",
            "nose",
            "mouth",
            "chest",
            "stomach",
            "leg",
            "toe",
            "foot",
            "hand",
            "arm",
            "shoulder",
            "buttocks",
            "heel",
            "wrist",
            "finger",
            "thigh",
            "calf",
            "lung",
            "liver",
            "intestines",
            "heart",
            "brain",
            "pancreas",
            "kidneys",
            "bladder",
        ],
    },
    {
        clue: "Book",
        choices: [
            "gone with the wind",
            "the alchemist",
            "the da vinci code",
            "great expectations",
            "to kill a mockingbird",
            "don quixote",
            "the great gatsby",
            "the adventures of huckleberry finn",
            "ulysses",
            "war and peace",
            "moby dick",
            "hamlet",
            "the catcher in the rye",
            "the odyssey",
            "the brothers karamazov",
            "crime and punishment",
            "madame bovary",
            "the divine comedy",
            "pride and prejudice",
            "wuthering heights",
            "to the lighthouse",
            "nineteen eighty four",
            "the iliad",
            "invisible man",
            "jane eyre",
            "one thousand and one nights",
            "the trial",
            "david copperfield",
            "the lord of the rings",
            "les miserables",
            "the old man and the sea",
            "for whom the bell tolls",
            "the color purple",
            "lord of the flies",
            "gone with the wind",
            "animal farm",
            "the canterbury tales",
            "frankenstein",
            "dracula",
            "a farewell to arms",
            "paradise lost",
            "faust",
            "robinson crusoe",
            "a clockwork orange",
            "the little prince",
            "treasure island",
            "the count of monte cristo",
            "the lion the with and the wardrobe",
            "king lear",
            "doctor zhivago",
            "of mice and men",
            "the hound of the baskervilles",
            "twenty thousand leagues under the sea",
            "the hobbit",
            "the stand",
            "winnie the pooh",
            "the three musketeers",
            "a tale of two cities",
            "pippi longstocking",
            "the maltese falcon",
            "tarzan of the apes",
            "war of the worlds",
            "macbeth",
            "go tell it on the mountain",
            "watership down",
            "the name of the rose",
            "the wonderful wizard of oz",
            "the english patient",
            "the tale of peter rabbit",
            "ivanhoe",
            "neuromancer",
            "satanic verses",
            "perfume",
        ],
    },
    {
        clue: "Color",
        choices: [
            "violet",
            "orange",
            "black",
            "brown",
            "cyan",
            "green",
            "yellow",
            "blue",
            "purple",
            "pink",
            "magenta",
            "white",
            "red",
            "orange",
            "gray",
            "cyan",
            "azure",
            "rose",
            "beige",
            "khaki",
        ],
    },
    {
        clue: "Country",
        choices: [
            "france",
            "united states of america",
            "turkey",
            "india",
            "netherlands",
            "canada",
            "belgium",
            "france",
            "germany",
            "peru",
            "chile",
            "japan",
            "australia",
            "new zealand",
            "china",
            "ukraine",
            "spain",
            "portugal",
            "italy",
            "greece",
            "iran",
            "iraq",
            "israel",
            "afghanistan",
            "albania",
            "algeria",
            "andorra",
            "angola",
            "argentina",
            "armenia",
            "austria",
            "bahamas",
            "belize",
            "benin",
            "bhutan",
            "bolivia",
            "brazil",
            "brunei",
            "bulgaria",
            "burundi",
            "cambodia",
            "cameroon",
            "chad",
            "colombia",
            "costa rica",
            "croatia",
            "cuba",
            "denmark",
            "sweden",
            "norway",
            "finland",
            "iceland",
            "dominican republic",
            "ecuador",
            "egypt",
            "estonia",
            "ethiopia",
            "fiji",
            "gambia",
            "ghana",
            "guatemala",
            "guinea",
            "guyana",
            "haiti",
            "honduras",
            "hungary",
            "indonesia",
            "ireland",
            "jamaica",
            "kazakhstan",
            "kenya",
            "laos",
            "lebanon",
            "libya",
            "liechtenstein",
            "monaco",
            "lithuania",
            "luxembourg",
            "madagascar",
            "malaysia",
            "malawi",
            "malta",
            "mauritania",
            "mauritius",
            "mexico",
            "mongolia",
            "morocco",
            "mozambique",
            "namibia",
            "nepal",
            "nicaragua",
            "niger",
            "nigeria",
            "north korea",
            "south korea",
            "oman",
            "pakistan",
            "panama",
            "paraguay",
            "philippines",
            "poland",
            "qatar",
            "romania",
            "russia",
            "rwanda",
            "saint kitts and nevis",
            "saint lucia",
            "samoa",
            "san marino",
            "saudi arabia",
            "senegal",
            "serbia",
            "seychelles",
            "sierra leone",
            "singapore",
            "slovakia",
            "slovenia",
            "somalia",
            "south africa",
            "suriname",
            "switzerland",
            "syria",
            "tanzania",
            "thailand",
            "togo",
            "tonga",
            "trinidad and tobago",
            "tunisia",
            "uganda",
            "united arab emirates",
            "united kingdom",
            "uruguay",
            "venezuela",
            "vietnam",
            "yemen",
            "zambia",
            "zimbabwe",
            "canada",
        ],
    },
    {
        clue: "Capital Cities",
        choices: [
            "beijing",
            "paris",
            "london",
            "berlin",
            "washington d c",
            "tokyo",
            "madrid",
            "lisbon",
            "amsterdam",
            "kabul",
            "algiers",
            "buenos aires",
            "canberra",
            "vienna",
            "baku",
            "nassau",
            "minsk",
            "brussels",
            "porto novo",
            "la paz",
            "sarajevo",
            "brasilia",
            "sofia",
            "ouagadougou",
            "phnom penh",
            "ottawa",
            "santiago",
            "beijing",
            "bogota",
            "kinshasa",
            "san jose",
            "zagreb",
            "havana",
            "nicosia",
            "prague",
            "copenhagen",
            "helsinki",
            "oslo",
            "tallinn",
            "addis ababa",
            "budapest",
            "reykjavik",
            "new delhi",
            "jakarta",
            "tehran",
            "baghdad",
            "dublin",
            "rome",
            "kingston",
            "riga",
            "beirut",
            "tripoli",
            "monrovia",
            "luxembourg",
            "vilnius",
            "kuala lumpur",
            "mexico city",
            "rabat",
            "windhoek",
            "wellington",
            "kingstown",
            "moscow",
            "bucharest",
            "doha",
            "warsaw",
            "lima",
            "islamabad",
            "seoul",
            "pretoria",
            "bratislava",
            "madrid",
            "colombo",
            "paramaribo",
            "stockholm",
            "bern",
            "damascus",
            "bangkok",
            "tunis",
            "ankara",
            "caracas",
            "hanoi",
            "harare",
            "montevideo",
        ],
    },
    {
        clue: "Food",
        choices: [
            "pizza",
            "pasta",
            "donut",
            "sushi",
            "ramen",
            "nougat",
            "bruschetta",
            "pepperoni",
            "gyros",
            "grilled cheese",
            "churros",
            "miso soup",
            "parfait",
            "pavlova",
            "nori",
            "mooncake",
            "macaroni",
            "guacamole",
            "fondue",
            "quesadilla",
            "chocolate chip cookie",
            "naan",
            "chutney",
            "fish and chips",
            "pad thai",
            "fajitas",
            "sundae",
            "hummus",
            "nachos",
            "burrito",
            "fried chicken",
            "fudge",
            "barbecue",
            "kimchi",
            "biryani",
            "wonton",
            "pretzel",
            "quiche",
            "tiramisu",
            "macarons",
            "lasagna",
            "milkshake",
            "roti",
            "yakitori",
            "mac and cheese",
            "cheeseburger",
            "brownies",
            "paella",
            "dim sum",
            "spaghetti",
            "tortilla",
            "sashimi",
            "cupcake",
            "croissant",
            "tacos",
            "burger",
        ],
    },
    {
        clue: "Flower",
        choices: [
            "daisy",
            "orchid",
            "rose",
            "lily",
            "sunflower",
            "tulip",
            "daffodil",
            "poppy",
            "cherry blossom",
            "iris",
            "geranium",
            "lotus",
            "water lily",
            "dandelion",
            "hyacinth",
            "crocus",
            "amaryllis",
            "anemone",
            "aster",
            "azalea",
            "begonia",
            "bellflower",
            "clematis",
            "clover",
            "dahlia",
            "forsythia",
            "lavender",
            "lily of the valley",
            "marigold",
            "oleander",
            "pansy",
            "passion flower",
            "petunia",
            "phlox",
            "snowflake",
            "rose",
        ],
    },
    {
        clue: "Insect",
        choices: [
            "beetle",
            "fly",
            "ant",
            "cricket",
            "butterfly",
            "mosquito",
            "ladybird",
            "flea",
            "earwig",
            "termite",
            "mantis",
            "dragonfly",
            "wasp",
            "cockroach",
            "blow fly",
            "moth",
            "damselfly",
            "dung beetle",
            "locust",
            "gnat",
            "sandfly",
            "woodworm",
            "twig borer",
            "grasshopper",
            "glowworm",
            "army ant",
        ],
    },
    {
        clue: "Musical Instrument",
        choices: [
            "piano",
            "guitar",
            "ukulele",
            "saxophone",
            "violin",
            "cello",
            "trombone",
            "trumpet",
            "tuba",
            "french horn",
            "clarinet",
            "harp",
            "keyboad",
            "xylophone",
            "maracas",
            "bell",
            "harmonica",
            "accordion",
            "drums",
            "banjo",
            "bass guitar",
            "conga",
            "bugle",
            "flute",
            "organ",
            "sitar",
            "tambourine",
            "triangle",
            "bassoon",
            "castanets",
            "didgeridoo",
            "gong",
            "harpsichord",
            "lute",
            "mandolin",
            "oboe",
            "piccolo",
            "viola",
            "bagpipes",
            "boomwhacker",
            "bongo",
            "bullroarer",
            "chimes",
            "claves",
            "coconut shells",
            "comb",
            "cowbell",
            "dobro",
            "kantele",
            "keytar",
            "lyre",
            "melodica",
            "sleigh bells",
            "slide whistle",
            "theremin",
            "vuvuzela",
            "washboard",
            "wood block",
        ],
    },
    {
        clue: "Number",
        choices: [
            "four",
            "five",
            "hundred",
            "ten",
            "two",
            "one",
            "three",
            "six",
            "zero",
            "seven",
            "eight",
            "nine",
            "eleven",
            "twelve",
            "thirteen",
            "fourteen",
            "fifteen",
            "sixteen",
            "seventeen",
            "eighteen",
            "nineteen",
            "twenty",
            "thirty",
            "forty",
            "fifty",
            "sixty",
            "seventy",
            "eighty",
            "ninety",
            "thousand",
            "million",
            "billion",
            "trillion",
            "quadrillion",
            "quintillion",
            "sextillion",
            "googol",
            "googolplex",
        ],
    },
    {
        clue: "Profession",
        choices: [
            "teacher",
            "engineer",
            "lawyer",
            "accountant",
            "dentist",
            "surgeon",
            "architect",
            "pharmacist",
            "electrician",
            "waiting staff",
            "cook",
            "technician",
            "secretary",
            "librarian",
            "physician",
            "veterinarian",
            "dentist",
            "scientist",
            "chef",
            "actor",
            "labourer",
            "police officer",
            "plumber",
            "firefighter",
            "hairdresser",
            "software developer",
            "aviator",
            "tailor",
            "psychologist",
            "designer",
            "optician",
            "artist",
            "mail carrier",
            "cleaner",
            "dietitian",
            "lifeguard",
            "mechanic",
            "economist",
            "baker",
            "bus driver",
            "surveyor",
            "butcher",
            "occupational therapist",
            "author",
            "cashier",
            "farmer",
            "bartender",
            "dental hygienist",
            "tour guide",
            "actuary",
            "journalist",
            "geologist",
            "graphic designer",
        ],
    },
    {
        clue: "Shape",
        choices: [
            "triangle",
            "circle",
            "cube",
            "cuboid",
            "octagon",
            "pentagon",
            "nonagon",
            "hexagon",
            "parallelogram",
            "rhombus",
            "square",
            "oval",
            "heart",
            "cross",
            "arrow",
            "cylinder",
            "star",
            "crescent",
            "heptagon",
            "scalene triangle",
            "right triangle",
            "rectangle",
            "kite",
            "trapezium",
            "trapezoid",
            "decagon",
            "ellipse",
            "sphere",
            "ellipsoid",
            "cone",
            "prism",
            "pyramid",
            "tetrahedon",
            "octahedron",
            "round",
        ],
    },
    {
        clue: "Sport",
        choices: [
            "cricket",
            "basketball",
            "hockey",
            "tennis",
            "volleyball",
            "soccer",
            "aikido",
            "american football",
            "kayaking",
            "bobsleigh",
            "rafting",
            "skeleton",
            "snorkeling",
            "bodyboarding",
            "diving",
            "freediving",
            "paddle boarding",
            "rowing",
            "scuba diving",
            "surfing",
            "synchronized swimming",
            "aerobics",
            "archery",
            "artistic gymnastics",
            "baron twirling",
            "bodybuilding",
            "boxing",
            "cycling",
            "discus throw",
            "fencing",
            "figure skating",
            "horseback riding",
            "horse racing",
            "judo",
            "karate",
            "kendo",
            "kickboxing",
            "kung fu",
            "long jump",
            "marathon",
            "mixed martial arts",
            "muay thai",
            "pole vault",
            "powerlifting",
            "racewalking",
            "rhythmic gymnastics",
            "sprint",
            "sumo",
            "trail running",
            "trampolining",
            "tumbling",
            "ultimate frisbee",
            "walking",
            "weightlifting",
            "baseball",
            "badminton",
            "bowling",
            "curling",
            "dodgeball",
            "football",
            "golf",
            "handball",
            "hurling",
            "ice hockey",
            "lacrosse",
            "polo",
            "rugby",
            "softball",
            "table tennis",
            "skydiving",
            "kitesurfing",
            "paragliding",
            "skateboarding",
            "skiing",
            "snowboarding",
            "windsurfing",
            "hiking",
            "drifting",
            "kart racing",
            "rallycross",
        ],
    },
    {
        clue: "video Game",
        choices: [
            "Pacman",
            "Minecraft",
            "Grand Theft Auto",
            "Angry Birds",
            "Tetris",
            "World of Warcraft",
            "Pokemon Go",
            "Borderlands",
            "Final Fantasy",
            "The Secret of Monkey Island",
            "League of Legends",
            "SimCity",
            "Fortnite",
            "Donkey Kong",
            "The Sims",
            "Rock Band",
            "Red Dead Redemption",
            "Overwatch",
            "Deus Ex",
            "Resident Evil",
            "Bloodborne",
            "God of War",
            "The Last of Us",
            "Doom",
            "Wolfenstein",
            "Super Mario World",
            "Gone Home",
            "Silent Hill",
            "Day of the Tentacle",
            "Leisure Suit Larry",
            "Space Quest",
            "Kings Quest",
            "Police Quest",
            "Zork",
            "Dungeon Master",
            "Twisted Metal",
            "Gran Turismo",
            "Prince of Persia",
            "Double Dragon",
            "Mortal Kombat",
            "Kingdom Hearts",
            "Myst",
            "Pitfall",
            "Grim Fandango",
            "Gauntlet",
            "Journey",
            "Tomb Raider",
            "Dark Souls",
            "Skyrim",
            "Super Metroid",
            "Civilization",
            "Sonic the Hedgehog",
            "StarCraft",
            "Asteroids",
            "Pong",
            "Metal Gear Solid",
            "Super Mario Kart",
            "BioShock",
            "Super Mario World",
            "Limbo",
            "Forza Horizon",
            "Rocket League",
            "Spelunky",
            "Wii Sports",
            "Guitar Hero",
        ],
    },
    {
        clue: "Movie",
        choices: [
            "Inception",
            "Interstellar",
            "The Wolf of Wall Street",
            "Back to the Future",
            "The Shining",
            "Jurassic Park",
            "Vertigo",
            "Citizen Kane",
            "Tokyo Story",
            "Apocalypse Now",
            "Platoon",
            "A Bridge Too Far",
            "Mirror",
            "The Godfather",
            "Taxi Driver",
            "Psycho",
            "A Nightmare on Elm Street",
            "Halloween",
            "Some Like it Hot",
            "The Seven Samurai",
            "Bonnie and Clyde",
            "Reservoir Dogs",
            "Airplane",
            "Doctor Zhivago",
            "The Deer Hunter",
            "Close Encounters of the Third Kind",
            "Karate Kid",
            "Up",
            "Rocky",
            "Memento",
            "Braveheart",
            "Brave",
            "Frozen",
            "Slumdog Millionaire",
            "The Lord of the Rings",
            "Harry Potter",
            "Beauty and the Beast",
            "Seven",
            "Dumbo",
            "Bambi",
            "Die Hard",
            "Amadeus",
            "On the Waterfront",
            "Angry Men",
            "Ghostbusters",
            "Brokeback Mountain",
            "The Bridge on the River Kwai",
            "Blazing Saddles",
            "Young Frankenstein",
            "Dracula",
            "Almost Famous",
            "Gladiator",
            "Monty Python and the Holy Grail",
            "Avatar",
            "Titanic",
            "The Lion King",
            "Raging Bull",
            "Mary Poppins",
            "Groundhog Day",
            "North by Northwest",
            "West Side Story",
            "Grease",
            "Fame",
            "Amelie",
            "The Dark Knight",
            "Butch Cassidy and the Sundance Kid",
            "Good Will Hunting",
            "The Big Lebowski",
            "Saving Private Ryan",
            "Pearl Harbor",
            "The Matrix",
            "Toy Story",
            "Alien",
            "IT",
            "When Harry Met Sally",
            "A CLockwork Orange",
            "Fargo",
            "The Princess Bride",
            "Blade Runner",
            "The Breakfast Club",
            "The Sound of Music",
            "Jaws",
            "Lawrence of Arabia",
            "The Silence of the Lambs",
            "Chinatown",
            "Goodfellas",
            "Annie Hall",
            "Apocalypse Now",
            "To Kill a Mockingbird",
            "Gone With the Wind",
            "Forrest Gump",
            "Raiders of the Lost Ark",
            "Star Wars",
            "Casablanca",
            "Pulp Fiction",
            "The Shawshank Redemption",
            "The Wizard of Oz",
        ],
    },
    {
        clue: "TV Show",
        choices: [
            "Game of Thrones",
            "Breaking Bad",
            "The Walking Dead",
            "Friends",
            "Stranger Things",
            "Rick and Morty",
            "Buffy the Vampire Slayer",
            "Charmed",
            "Veep",
            "The Shield",
            "Planet Earth",
            "Lost",
            "Band of Brothers",
            "Borgen",
            "Six Feet Under",
            "Sherlock",
            "Orange is the New Black",
            "Sex and the City",
            "Utopia",
            "Downton Abbey",
            "Better Call Saul",
            "Doctor Who",
            "The Crown",
            "South Park",
            "The Good Wife",
            "Big Brother",
            "The Office",
            "Blue Planet",
            "Killing Eve",
            "Black Mirror",
            "Twin Peaks",
            "Deadwood",
            "The West Wing",
            "Mad Men",
            "The Wire",
            "The Sopranos",
            "Happy Days",
            "Golden Girls",
            "Cheers",
            "Frasier",
            "Rome",
            "Boardwalk Empire",
            "Rick and Morty",
            "Hannibal",
            "ER",
            "The Wonder Years",
            "Hill Street Blues",
            "Chips",
            "House of Cards",
            "Airwolf",
            "Knight Rider",
            "The Muppet Show",
            "Roseanne",
            "Fargo",
            "Fawlty Towers",
            "Sesame Street",
            "The Cosby Show",
            "Battlestar Galactica",
            "Buck Rogers",
            "Seinfeld",
            "I Love Lucy",
            "The Twilight Zone",
        ],
    },
    {
        clue: "Superhero / Villain",
        choices: [
            "Superman",
            "Wolverine",
            "Captain America",
            "Hulk",
            "Batman",
            "the Flash",
            "aquaman",
            "batwoman",
            "thor",
            "hal jordan",
            "thing",
            "mr fantastic",
            "invisible woman",
            "human torch",
            "silver surfer",
            "supergirl",
            "daredevil",
            "iron man",
            "cyborg",
            "beast boy",
            "starfire",
            "raven",
            "black panther",
            "aquaman",
            "wonder woman",
            "green arrow",
            "leonardo",
            "raphael",
            "donatello",
            "michelangelo",
            "professor x",
            "doctor strange",
            "hawkeye",
            "firestorm",
            "hawkman",
            "nick fury",
            "phantom stranger",
            "black widow",
            "angel",
            "atom",
            "captain marvel",
            "conan",
            "hercules",
            "gambit",
            "war machine",
            "spectre",
            "rogue",
            "storm",
            "punisher",
            "green lantern",
            "spider-man",
            "catwoman",
            "thanos",
            "wanda maximoff",
            "joker",
            "deadpool",
            "wasp",
            "cyclops",
            "loki",
            "harley quinn",
            "vision",
            "elektra",
            "magneto",
            "poison ivy",
            "ghost rider",
        ],
    },
    {
        clue: "Vegetable",
        choices: [
            "Carrot",
            "Potato",
            "Tomato",
            "Onion",
            "Broccoli",
            "Mushroom",
            "artichoke",
            "asparagus",
            "bamboo shoots",
            "beans",
            "beets",
            "brussel sprouts",
            "cabbage",
            "cassava",
            "cauliflower",
            "celery",
            "chicory",
            "corn",
            "cucumber",
            "eggplant",
            "fennel",
            "kale",
            "lettuce",
            "okra",
            "parsnip",
            "peas",
            "green pepper",
            "pumpkin",
            "radicchio",
            "radishes",
            "shallots",
            "spinach",
            "sweet potato",
            "sugar snap peas",
            "turnip",
            "watercress",
            "zucchini",
            "leeks",
            "alfalfa sprouts",
            "bell peppers",
            "bok choy",
            "beetroot",
            "capsicum",
        ],
    },
    {
        clue: "Mineral",
        choices: [
            "aluminium",
            "antimony",
            "arsenic",
            "bismuth",
            "carbon",
            "cadmium",
            "chromium",
            "cobalt",
            "copper",
            "gold",
            "indium",
            "iron",
            "iridium",
            "lead",
            "manganese",
            "mercury",
            "molybdenum",
            "nickel",
            "niobium",
            "osmium",
            "palladium",
            "platinum",
            "rhenium",
            "rhodium",
            "selenium",
            "silver",
            "silicon",
            "sulfur",
            "tantalum",
            "tellurium",
            "tin",
            "titanium",
            "tungsten",
            "vanadium",
            "zinc",
        ],
    },
    {
        clue: "Scientist",
        choices: [
            "Albert Einstein",
            "Marie Curie",
            "Isaac Newton",
            "Charles Darwin",
            "Nikola Tesla",
            "Galileo Galilei",
            "Marie Curie",
            "Stephen Hawking",
            "Michael Faraday",
            "Nicolaus Copernicus",
            "Niels Bohr",
            "Charles Darwin",
            "James Watson",
            "Richard Feynman",
            "Carl Linnaeus",
            "Enrico Fermi",
            "Rachel Carson",
            "Thomas Edison",
            "Antoine Henri Becquerel",
            "J J Thomson",
            "Francis Crick",
            "Rosalind Franklin",
            "Louis Pasteur",
            "Joseph Priestley",
            "Max Planck",
            "Edmond Halley",
            "Wilhelm Rontgen",
            "Aristotle",
            "Leonhard Euler",
            "Archimedes",
            "Leonarda da Vinci",
            "Ada Lovelace",
            "John Dalton",
            "William Thomson",
            "Gregor Mendel",
            "Nikola Tesla",
            "Benjamin Franklin",
            "Edwin Hubble",
            "Robert Hooke",
            "Heinrich Hertz",
            "Alessandro Volta",
            "James Clerk Maxwell",
            "Charles Babbage",
            "Gottfried Wilhelm Leibniz",
            "Antoine Lavoisier",
            "Carl Sagan",
            "Hermann von Helmholtz",
            "Ernest Rutherford",
            "Maurice Wilkins",
            "Robert Boyle",
            "John von Neumann",
            "Alfred Nobel",
            "Blaise Pascal",
            "Andre Marie Ampere",
            "Carl Friedrich Gauss",
            "Georg Ohm",
            "Bill Nye",
            "Charles Babbage",
            "Alexander Graham Bell",
            "Max Planck",
            "Hermann Rorschach",
            "Neil deGrasse Tyson",
            "Alan Turing",
            "Anders Celsius",
            "Gottlieb Daimler",
            "Euclid",
            "Henry Ford",
            "Dian Fossey",
            "James Watt",
            "Sigmund Freud",
        ],
    },
    {
        clue: "Planet",
        choices: [
            "mercury",
            "venus",
            "earth",
            "mars",
            "jupiter",
            "saturn",
            "uranus",
            "neptune",
        ],
    },
    {
        clue: "Social Media",
        choices: [
            "facebook",
            "whatsapp",
            "wechat",
            "instagram",
            "twitter",
            "telegram",
            "youtube",
            "messenger",
            "quora",
            "tumblr",
            "tiktok",
            "qq",
            "reddit",
            "baidu tieba",
            "linkedin",
            "yelp",
            "snapchat",
            "pinterest",
            "vk",
            "deviantart",
            "discord",
            "mix",
            "tagged",
            "nextdoor",
            "meetup",
            "reverbnation",
            "flixster",
            "goodreads",
            "twitch",
            "caringbridge",
            "wattpad",
            "viadeo",
            "classmates",
            "flickr",
            "soundcloud",
            "bubbly",
            "collegehumor",
            "couchsurfing",
            "etoro",
            "xing",
            "meetme",
            "yy",
            "giphy",
            "medium",
            "line",
            "myspace",
            "imgur",
            "vimeo",
        ],
    },
    {
        clue: "Landmark",
        choices: [
            "taj mahal",
            "statue of liberty",
            "great sphinx",
            "pantheon",
            "the gateway arch",
            "eiffel tower",
            "golden gate bridge",
            "big ben",
            "great pyramid of giza",
            "sydney opera house",
            "empire state building",
            "forbidden city",
            "great wall of china",
            "machu picchu",
            "acropolis",
            "christ the redeemer",
            "burj khalifa",
            "angkor wat",
            "statue of unity",
            "nasir ol molk mosque",
            "leaning tower of pisa",
            "mount rushmore national memorial",
            "mont saint michel",
            "easter island",
            "neuschwanstein castle",
            "victoria falls",
            "the western wall",
            "buckingham palace",
            "la sagrada familia",
            "blue mosque",
            "the colosseum",
            "the grand palace",
            "petra",
            "ha long bay",
            "stonehenge",
            "blue domes of oia",
        ],
    },
    {
        clue: "Music Artist",
        choices: [
            "Lady Gaga",
            "Taylor Swift",
            "Harry Styles",
            "Mariah Carey",
            "Coldplay",
            "Ed Sheeran",
            "Eminem",
            "Michael Jackson",
            "Bob Dylan",
            "Elton John",
            "Elvis Presley",
            "Beyonce",
            "Chuck Berry",
            "Janet Jackson",
            "Otis Redding",
            "Eric Clapton",
            "B B King",
            "Kanye West",
            "David Bowie",
            "Bruce Springsteen",
            "Rihanna",
            "Neil Young",
            "Bob Marley",
            "Jay Z",
            "Drake",
            "James Brown",
            "Marvin Gaye",
            "Prince",
            "L L Cool J",
            "Lenny Kravitz",
            "John Mayall",
            "Amy Winehouse",
            "Adele",
            "Dusty Springfield",
            "Justin Timberlake",
            "Stevie Wonder",
            "Ray Charles",
            "Johnny Cash",
            "Nicki Minaj",
            "Rod Stewart",
            "Buddy Holly",
            "Snoop Dog",
            "Tupac Shakur",
            "Mary J Blige",
            "Dr Dre",
            "Bo Diddley",
            "Little Richard",
            "Madonna",
            "Willie Nelsen",
            "Katy Perry",
            "Iron Maiden",
            "Black Sabbath",
            "Ozzy Osbourne",
            "Deep Purple",
            "The Rolling Stones",
            "Miles Davis",
            "Billie Holiday",
            "Louis Armstrong",
            "Pearl Jam",
            "The Beatles",
            "Pink Floyd",
            "Adam and the Ants",
            "Alan Parsons",
            "Annie Lennox",
            "Arctic Monkeys",
            "Bauhaus",
            "Beck",
            "Billy Idol",
            "Bjork",
            "Blondie",
            "Blur",
            "Carlos Santana",
            "Chic",
            "Cliff Richard",
            "Chris Isaak",
            "Cream",
            "The Cranberries",
            "The Cure",
            "Devo",
            "Dizzy Gillespie",
            "Duke Ellington",
            "Elvis Costello",
            "Eurythmics",
            "Fats Domino",
            "Frank Sinatra",
            "Foo Fighters",
            "Fleetwood Mac",
            "Frank Zappa",
            "George Michael",
            "Wham",
            "Green Day",
            "Metallica",
            "Guns N Roses",
            "Iggy Pop",
            "James Brown",
            "Jeff Buckley",
            "Jimi Hendrix",
            "John Coltrane",
            "Joy Division",
            "Kasabian",
            "Kate Bush",
            "Kiss",
            "Led Zeppelin",
            "Madness",
            "Manic Street Preachers",
            "Marilyn Manson",
            "Morrissey",
            "Muddy Waters",
            "Mumford and Sons",
            "Muse",
            "New Order",
            "Nick Cave",
            "Nina Simone",
            "Nirvana",
            "Oasis",
            "Offspring",
            "The Police",
            "Phish",
            "Pulp",
            "Queen",
            "Radiohead",
            "The Ramones",
            "Red Hot Chili Peppers",
            "Sex Pistols",
            "Simply Red",
            "Siouxsie and the Banshees",
            "Slash",
            "Sonic Youth",
            "Status Quo",
            "Stereophonics",
            "Stone Roses",
            "Thin Lizzy",
            "Tina Turner",
            "Tom Jones",
            "Tom Waits",
            "The Who",
            "The Yardbirds",
        ],
    },
    {
        clue: "Fruit",
        choices: [
            "guava",
            "apple",
            "orange",
            "banana",
            "fig",
            "coconut",
            "pear",
            "melon",
            "apricot",
            "avocado",
            "blackberry",
            "blueberry",
            "cloudberry",
            "coconut",
            "date",
            "durian",
            "grape",
            "grapefruit",
            "guava",
            "kumquat",
            "lemon",
            "lime",
            "lychee",
            "mango",
            "mandarine",
            "tangerine",
            "papaya",
            "peach",
            "passionfruit",
            "plum",
            "pineapple",
            "pomelo",
            "rambutan",
            "raspberry",
            "strawberry",
            "tomato",
            "cherry",
            "goji berry",
            "jujube",
            "mulberry",
            "prune",
            "pomegranate",
            "tamarind",
        ],
    },
    {
        clue: "Fictional Character",
        choices: [
            "sherlock holmes",
            "james bond",
            "hermione granger",
            "bugs bunny",
            "captain jack sparrow",
            "spock",
            "gandalf",
            "bilbo baggins",
            "ebenezer scrooge",
            "quasimodo",
            "hercule poirot",
            "batman",
            "darth vader",
            "superman",
            "ichabod crane",
            "bugs bunny",
            "big bird",
            "hannibal lecter",
            "cheshire cat",
            "gollum",
            "ali baba",
            "frodo baggins",
            "don camillo",
            "conan the barbarian",
            "don quixote",
            "huckleberry finn",
            "frankenstein",
            "fu manchu",
            "humpty dumpty",
            "mr hyde",
            "isolde",
            "jabberwock",
            "dr jekyll",
            "juliet",
            "romeo",
            "inspector lestrade",
            "macbeth",
            "mad hatter",
            "miss marple",
            "perry mason",
            "mickey mouse",
            "dorothy gale",
            "indiana jones",
            "rocky balboa",
            "vito corleone",
            "han solo",
            "homer simpson",
            "archie bunker",
            "norman bates",
            "king kong",
            "barbie",
            "godzilla",
            "popeye",
            "forrest gump",
            "hannibal lector",
            "tony montana",
            "tony soprano",
            "the terminator",
            "jon snow",
            "marty mcfly",
            "charlie brown",
            "e t",
            "jay gatsby",
            "lassie",
            "fred flintstone",
            "atticus finch",
            "kermit the frog",
            "yoda",
            "mario",
            "harry potter",
            "willy wonka",
            "the dude",
            "edward scissorhands",
            "pikachu",
            "bambi",
            "wolverine",
            "freddy krueger",
            "jason voorhees",
            "betty boop",
            "cliff huxtable",
            "porky pig",
            "optimus prime",
            "sonic the hedgehog",
            "harry callahan",
            "professor moriarty",
            "captain nemo",
            "ophelia",
            "peter pan",
            "pinocchio",
            "piglet",
            "mary poppins",
            "allan quatermain",
            "robin hood",
            "shrek",
            "long john silver",
            "tarzan",
            "william tell",
            "tinker bell",
            "oliver twist",
            "uncle tom",
            "dr watson",
            "zorro",
        ],
    },
];
export default categories;
